"use client"
import { useState, useEffect, useMemo } from "react"
import { X, RefreshCw } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Badge } from "@/components/ui/badge"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"
import { generateCustomerTags } from "@/lib/customer-tags"
import { useAdminCache } from "@/hooks/use-admin-cache"

interface ExtendedCustomer {
  id: string
  first_name: string
  last_name: string
  email: string
  street?: string
  house_number?: string
  postal_code?: string
  city?: string
  phone?: string
  tags: string[]
  // New fields
  account_status?: "has_account" | "no_account"
  customer_status?: "active" | "inactive" | "blocked"
  registration_date?: string
  last_activity?: string
  newsletter_subscribed?: boolean
  reminder_notifications?: boolean
  special_requests?: string
  referral_source?: string
  distribution_system_benefits?: {
    participated: boolean
    total_benefits: number
    last_benefit_date?: string
  }
  order_count?: number
  average_order_value?: number
  favorite_categories?: string[]
  total_orders?: number
  total_spent?: number
  last_order_date?: string
  hellocash_user_id?: string // Added for HelloCash sync
  default_pickup_location_id?: string
  default_distribution_person_id?: string
}

interface CustomerEditModalProps {
  customer: ExtendedCustomer | null
  isOpen: boolean
  onClose: () => void
  onSave: (customer: ExtendedCustomer) => Promise<void>
  availableTags: string[]
  onAddTag: (tag: string) => void
}

export default function CustomerEditModal({
  customer,
  isOpen,
  onClose,
  onSave,
  availableTags,
  onAddTag,
}: CustomerEditModalProps) {
  const [editingCustomer, setEditingCustomer] = useState<ExtendedCustomer | null>(customer)
  const [newTag, setNewTag] = useState("")
  const [saving, setSaving] = useState(false)
  const [syncing, setSyncing] = useState(false)
  const [syncStatus, setSyncStatus] = useState<string>("")

  const { data: pickupLocationsData } = useAdminCache<{ locations: any[] }>("/api/admin/pickup-locations", {
    locations: [],
  })
  const pickupLocations = Array.isArray(pickupLocationsData?.locations)
    ? pickupLocationsData.locations.filter((loc: any) => loc.is_active)
    : []

  const { data: distributionPersonsData } = useAdminCache<{ persons: any[] }>("/api/admin/distribution-persons", {
    persons: [],
  })
  const distributionPersons = Array.isArray(distributionPersonsData?.persons)
    ? distributionPersonsData.persons.filter((person: any) => person.is_active)
    : []

  const autoGeneratedTags = useMemo(() => {
    if (!editingCustomer) return []
    return generateCustomerTags({
      customer_segment: editingCustomer.customer_segment,
      preferred_products: editingCustomer.preferred_products,
      favorite_categories: editingCustomer.favorite_categories,
      total_orders: editingCustomer.total_orders,
      total_spent: editingCustomer.total_spent,
      newsletter_subscribed: editingCustomer.newsletter_subscribed,
      reminder_notifications: editingCustomer.reminder_notifications,
      customer_status: editingCustomer.customer_status,
      account_status: editingCustomer.account_status,
    })
  }, [editingCustomer])

  const allAvailableTags = useMemo(() => {
    const combined = [...autoGeneratedTags, ...availableTags]
    return Array.from(new Set(combined)).sort()
  }, [autoGeneratedTags, availableTags])

  useEffect(() => {
    console.log("[v0] CustomerEditModal - customer prop changed:", customer)
    setEditingCustomer(customer)
  }, [customer])

  const handleSave = async () => {
    if (!editingCustomer) return

    console.log("[v0] CustomerEditModal - saving customer:", editingCustomer)
    const customerToSave = {
      ...editingCustomer,
      default_pickup_location_id: editingCustomer.default_pickup_location_id || null,
      default_distribution_person_id: editingCustomer.default_distribution_person_id || null,
    }
    console.log("[v0] CustomerEditModal - customerToSave with IDs:", customerToSave)

    setSaving(true)
    try {
      await onSave(customerToSave)
      onClose()
    } catch (error) {
      console.error("[v0] Error saving customer:", error)
    } finally {
      setSaving(false)
    }
  }

  const handleHelloCashSync = async () => {
    if (!editingCustomer?.id) return

    setSyncing(true)
    setSyncStatus("")

    try {
      const hasHelloCashId = !!(editingCustomer as any).hellocash_user_id

      // First save the current customer data
      console.log("[v0] Saving customer data before sync...")
      await onSave(editingCustomer)

      console.log("[v0] Syncing with HelloCash:", hasHelloCashId ? "Updating existing user" : "Creating new user")

      const method = hasHelloCashId ? "PUT" : "POST"
      const response = await fetch("/api/admin/hellocash/users", {
        method,
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ customerId: editingCustomer.id }),
      })

      if (!response.ok) {
        const error = await response.json()
        throw new Error(error.error || "Synchronisation fehlgeschlagen")
      }

      const result = await response.json()
      setSyncStatus(
        hasHelloCashId
          ? "✓ Kundendaten erfolgreich aktualisiert"
          : `✓ Kunde erfolgreich erstellt (ID: ${result.userId})`,
      )

      // Refresh customer data to get the new hellocash_user_id
      setTimeout(() => {
        setSyncStatus("")
      }, 3000)
    } catch (error: any) {
      console.error("[v0] HelloCash sync error:", error)
      setSyncStatus(`✗ Fehler: ${error.message}`)
    } finally {
      setSyncing(false)
    }
  }

  const addCustomTag = () => {
    if (newTag.trim() && !allAvailableTags.includes(newTag.trim())) {
      onAddTag(newTag.trim())
      setNewTag("")
    }
  }

  const addTagToCustomer = (tag: string) => {
    if (editingCustomer && !editingCustomer.tags.includes(tag)) {
      setEditingCustomer({
        ...editingCustomer,
        tags: [...(editingCustomer.tags || []), tag],
      })
    }
  }

  const removeTagFromCustomer = (tagToRemove: string) => {
    if (editingCustomer) {
      setEditingCustomer({
        ...editingCustomer,
        tags: (editingCustomer.tags || []).filter((tag) => tag !== tagToRemove),
      })
    }
  }

  if (!editingCustomer) return null

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-[80rem] sm:max-w-[80rem] md:max-w-[80rem] lg:max-w-[80rem] max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Kunde bearbeiten</DialogTitle>
          <DialogDescription>
            Bearbeiten Sie die Kundendaten und klicken Sie auf "Speichern", um die Änderungen zu übernehmen.
          </DialogDescription>
        </DialogHeader>

        <div className="grid grid-cols-2 gap-4 py-4">
          <div className="space-y-2">
            <Label htmlFor="first_name">Vorname</Label>
            <Input
              id="first_name"
              value={editingCustomer.first_name || ""}
              onChange={(e) => setEditingCustomer({ ...editingCustomer, first_name: e.target.value })}
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="last_name">Nachname</Label>
            <Input
              id="last_name"
              value={editingCustomer.last_name || ""}
              onChange={(e) => setEditingCustomer({ ...editingCustomer, last_name: e.target.value })}
            />
          </div>
          <div className="space-y-2 col-span-2">
            <Label htmlFor="email">E-Mail</Label>
            <Input
              id="email"
              type="email"
              value={editingCustomer.email || ""}
              onChange={(e) => setEditingCustomer({ ...editingCustomer, email: e.target.value })}
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="street">Straße</Label>
            <Input
              id="street"
              value={editingCustomer.street || ""}
              onChange={(e) => setEditingCustomer({ ...editingCustomer, street: e.target.value })}
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="house_number">Hausnummer</Label>
            <Input
              id="house_number"
              value={editingCustomer.house_number || ""}
              onChange={(e) => setEditingCustomer({ ...editingCustomer, house_number: e.target.value })}
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="postal_code">PLZ</Label>
            <Input
              id="postal_code"
              value={editingCustomer.postal_code || ""}
              onChange={(e) => setEditingCustomer({ ...editingCustomer, postal_code: e.target.value })}
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="city">Stadt</Label>
            <Input
              id="city"
              value={editingCustomer.city || ""}
              onChange={(e) => setEditingCustomer({ ...editingCustomer, city: e.target.value })}
            />
          </div>
          <div className="space-y-2 col-span-2">
            <Label htmlFor="phone">Telefon</Label>
            <Input
              id="phone"
              value={editingCustomer.phone || ""}
              onChange={(e) => setEditingCustomer({ ...editingCustomer, phone: e.target.value })}
            />
          </div>

          {/* Tags Management Section */}
          <div className="space-y-2 col-span-2">
            <Label>Tags verwalten</Label>

            {autoGeneratedTags.length > 0 && (
              <div className="p-2 bg-blue-50 border border-blue-200 rounded-md">
                <p className="text-xs text-blue-800 mb-1">
                  <strong>Automatisch generierte Tags:</strong> Diese Tags werden aus Kundendaten erstellt
                </p>
                <div className="flex flex-wrap gap-1">
                  {autoGeneratedTags.map((tag, index) => (
                    <Badge key={index} variant="outline" className="text-xs bg-blue-100 border-blue-300">
                      {tag}
                    </Badge>
                  ))}
                </div>
              </div>
            )}

            <div className="space-y-2">
              <Label className="text-sm font-medium">Aktuelle Tags:</Label>
              <div className="flex flex-wrap gap-2 min-h-[40px] p-2 border rounded-md bg-gray-50">
                {editingCustomer.tags && editingCustomer.tags.length > 0 ? (
                  editingCustomer.tags.map((tag: string, index: number) => (
                    <Badge key={index} variant="secondary" className="flex items-center gap-1">
                      {tag}
                      <X
                        className="h-3 w-3 cursor-pointer hover:text-red-500"
                        onClick={() => removeTagFromCustomer(tag)}
                      />
                    </Badge>
                  ))
                ) : (
                  <span className="text-gray-400 text-sm">Keine Tags zugewiesen</span>
                )}
              </div>
            </div>
            <div className="space-y-2">
              <Label className="text-sm font-medium">Tag hinzufügen:</Label>
              <Select onValueChange={addTagToCustomer}>
                <SelectTrigger>
                  <SelectValue placeholder="Verfügbare Tags auswählen" />
                </SelectTrigger>
                <SelectContent>
                  {allAvailableTags
                    .filter((tag) => !editingCustomer.tags?.includes(tag))
                    .map((tag) => (
                      <SelectItem key={tag} value={tag}>
                        {tag}
                      </SelectItem>
                    ))}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label className="text-sm font-medium">Neuen Tag erstellen:</Label>
              <div className="flex gap-2">
                <Input
                  placeholder="Neuen Tag eingeben..."
                  value={newTag}
                  onChange={(e) => setNewTag(e.target.value)}
                  onKeyPress={(e) => {
                    if (e.key === "Enter") {
                      e.preventDefault()
                      addCustomTag()
                    }
                  }}
                />
                <Button
                  type="button"
                  onClick={addCustomTag}
                  disabled={!newTag.trim() || allAvailableTags.includes(newTag.trim())}
                >
                  Hinzufügen
                </Button>
              </div>
            </div>
            <div className="space-y-2">
              <Label className="text-sm font-medium">Alle verfügbaren Tags:</Label>
              <div className="flex flex-wrap gap-1 max-h-20 overflow-y-auto p-2 border rounded-md bg-gray-50">
                {allAvailableTags.map((tag) => (
                  <Badge
                    key={tag}
                    variant="outline"
                    className={`text-xs cursor-pointer hover:bg-blue-100 ${
                      editingCustomer.tags?.includes(tag) ? "bg-blue-200" : ""
                    }`}
                    onClick={() => addTagToCustomer(tag)}
                  >
                    {tag}
                  </Badge>
                ))}
              </div>
            </div>
          </div>

          {/* New customer status fields */}
          <div className="space-y-2">
            <Label htmlFor="customer_status">Kundenstatus</Label>
            <Select
              value={editingCustomer?.customer_status || "active"}
              onValueChange={(value) =>
                setEditingCustomer({
                  ...editingCustomer!,
                  customer_status: value as "active" | "inactive" | "blocked",
                })
              }
            >
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="active">Aktiv</SelectItem>
                <SelectItem value="inactive">Inaktiv</SelectItem>
                <SelectItem value="blocked">Gesperrt</SelectItem>
              </SelectContent>
            </Select>
          </div>

          <div className="space-y-2">
            <Label htmlFor="account_status">Kontostatus</Label>
            <Select
              value={editingCustomer?.account_status || "no_account"}
              onValueChange={(value) =>
                setEditingCustomer({
                  ...editingCustomer!,
                  account_status: value as "has_account" | "no_account",
                })
              }
            >
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="has_account">Hat Konto</SelectItem>
                <SelectItem value="no_account">Kein Konto</SelectItem>
              </SelectContent>
            </Select>
          </div>

          {/* Communication preferences */}
          <div className="space-y-2">
            <Label>Newsletter-Abonnement</Label>
            <div className="flex items-center space-x-2">
              <input
                type="checkbox"
                id="newsletter_subscription"
                checked={editingCustomer?.newsletter_subscribed || false}
                onChange={(e) =>
                  setEditingCustomer({
                    ...editingCustomer!,
                    newsletter_subscribed: e.target.checked,
                  })
                }
                className="rounded border-gray-300"
              />
              <Label htmlFor="newsletter_subscription" className="text-sm">
                Newsletter abonniert
              </Label>
            </div>
          </div>

          <div className="space-y-2">
            <Label>Erinnerungsfunktion</Label>
            <div className="flex items-center space-x-2">
              <input
                type="checkbox"
                id="reminder_notifications"
                checked={editingCustomer?.reminder_notifications || false}
                onChange={(e) =>
                  setEditingCustomer({
                    ...editingCustomer!,
                    reminder_notifications: e.target.checked,
                  })
                }
                className="rounded border-gray-300"
              />
              <Label htmlFor="reminder_notifications" className="text-sm">
                Erinnerungen aktiviert
              </Label>
            </div>
          </div>

          {/* Pickup location dropdown */}
          <div className="space-y-2 col-span-2">
            <Label htmlFor="default_pickup_location">Standard-Abholort</Label>
            <Select
              value={editingCustomer?.default_pickup_location_id || "none"}
              onValueChange={(value) =>
                setEditingCustomer({
                  ...editingCustomer!,
                  default_pickup_location_id: value === "none" ? null : value,
                })
              }
            >
              <SelectTrigger>
                <SelectValue placeholder="Abholort wählen..." />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="none">Kein Standard-Abholort</SelectItem>
                {pickupLocations.map((location: any) => (
                  <SelectItem key={location.id} value={location.id}>
                    {location.name}
                    {location.city && ` - ${location.city}`}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            {editingCustomer?.default_pickup_location_id && (
              <p className="text-xs text-muted-foreground">
                Der Kunde wird automatisch diesem Abholort zugeordnet bei neuen Bestellungen
              </p>
            )}
          </div>

          {/* Distribution person dropdown */}
          <div className="space-y-2 col-span-2">
            <Label htmlFor="default_distribution_person">Standard-Verteilperson</Label>
            <Select
              value={editingCustomer?.default_distribution_person_id || "none"}
              onValueChange={(value) =>
                setEditingCustomer({
                  ...editingCustomer!,
                  default_distribution_person_id: value === "none" ? null : value,
                })
              }
            >
              <SelectTrigger>
                <SelectValue placeholder="Verteilperson wählen..." />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="none">Keine Standard-Verteilperson</SelectItem>
                {distributionPersons.map((person: any) => (
                  <SelectItem key={person.id} value={person.id}>
                    {person.name}
                    {person.city && ` - ${person.city}`}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            {editingCustomer?.default_distribution_person_id && (
              <p className="text-xs text-muted-foreground">
                Der Kunde wird automatisch dieser Verteilperson zugeordnet bei neuen Bestellungen
              </p>
            )}
          </div>

          {/* Referral source */}
          <div className="space-y-2">
            <Label htmlFor="referral_source">Empfehlungsquelle</Label>
            <Input
              id="referral_source"
              value={editingCustomer?.referral_source || ""}
              onChange={(e) =>
                setEditingCustomer({
                  ...editingCustomer!,
                  referral_source: e.target.value,
                })
              }
              placeholder="Wie hat der Kunde von uns erfahren?"
            />
          </div>

          {/* Special requests */}
          <div className="space-y-2 col-span-2">
            <Label htmlFor="special_requests">Besondere Wünsche</Label>
            <textarea
              id="special_requests"
              value={editingCustomer?.special_requests || ""}
              onChange={(e) =>
                setEditingCustomer({
                  ...editingCustomer!,
                  special_requests: e.target.value,
                })
              }
              placeholder="Notizen zu Kundenpräferenzen..."
              className="w-full p-2 border rounded-md resize-none h-20"
            />
          </div>
        </div>

        <DialogFooter>
          <div className="flex items-center gap-2 mr-auto">
            <Button
              variant="outline"
              onClick={handleHelloCashSync}
              disabled={syncing || saving}
              className="flex items-center gap-2 bg-transparent"
            >
              <RefreshCw className={`h-4 w-4 ${syncing ? "animate-spin" : ""}`} />
              {syncing ? "Synchronisiere..." : "Mit HelloCash synchronisieren"}
            </Button>
            {syncStatus && (
              <span className={`text-sm ${syncStatus.startsWith("✓") ? "text-green-600" : "text-red-600"}`}>
                {syncStatus}
              </span>
            )}
          </div>
          <Button variant="outline" onClick={onClose} disabled={saving}>
            Abbrechen
          </Button>
          <Button onClick={handleSave} disabled={saving}>
            {saving ? "Speichere..." : "Speichern"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
